### ISSUE TITLE
Epel-Release Package Required on CentOS 7

### ISSUE THREAD

**Issue by rellerreller** [erjac77/ansible-role-docker#5]
The installation of the role failed when it tried to install the pip packages. This is because pip is not installed. The code tries to install it as part of pip dependencies, but it fails if the epel repository is not enabled.

Steps to recreate:
1. Min install of CentOS 7 1810
2. Run ansible-playbook using the playbook below

Ansible Playbook that Fails
```
---

- hosts: dockers
  become: yes
  roles:
  - erjac77.docker
```

The playbook below will fix the issue, but I think this would be better in the role.

Ansible Playbook Workaround
```
---

- hosts: dockers
  become: yes
  pre_tasks:
  - name: Install epel-release
    yum:
      name: epel-release
      state: present
  roles:
  - erjac77.docker
```

Thanks for posting the code. It's good.
